services:
  - type: web
    name: billing-backend
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install -r Billing_Backend/requirements.txt
    startCommand: uvicorn Billing_Backend.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SERVICE
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
